
branches:
  only:
    - master

skip_tags: true

image: Visual Studio 2017

environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version

build_script:
  - ps: .\build.ps1 -Target Deploy
